export const COLORS = {
  HALL_OF_FAME_BLACK: '#222',
  HALL_OF_FAME_BLUE: '#456990',
  HALL_OF_FAME_GREEN: '#49DCB1',
  HALL_OF_FAME_WHITE: '#F7F9F9',
  HALL_OF_FAME_YELLOW: '#EEB868',
  HALL_OF_FAME_RED: '#EF767A'
}
